import type {
  User,
  EventItem,
  Registration,
  Certificate,
  AppNotification,
  Feedback,
} from "@/constants/types"

// ---------------------------------------------------------------------------
// In-memory mock database. Swap this module (and mockClient.ts) for real
// Axios calls against the Express backend later — the API layer signatures
// in src/api/*.ts stay the same.
// ---------------------------------------------------------------------------

const now = new Date()
const daysFromNow = (d: number, h = 10) => {
  const dt = new Date(now)
  dt.setDate(dt.getDate() + d)
  dt.setHours(h, 0, 0, 0)
  return dt.toISOString()
}

export const users: User[] = [
  {
    id: "u1",
    name: "Rahul Sharma",
    email: "user@demo.com",
    role: "USER",
    joinedAt: daysFromNow(-120),
  },
  {
    id: "u2",
    name: "Priya Patel",
    email: "priya@demo.com",
    role: "USER",
    joinedAt: daysFromNow(-90),
  },
  {
    id: "o1",
    name: "GDG Campus Club",
    email: "organizer@demo.com",
    role: "ORGANIZER",
    organization: "Google Developer Group",
    verified: true,
    joinedAt: daysFromNow(-300),
  },
  {
    id: "o2",
    name: "Startup Circle",
    email: "circle@demo.com",
    role: "ORGANIZER",
    organization: "Startup Circle NGO",
    verified: false,
    joinedAt: daysFromNow(-45),
  },
  {
    id: "a1",
    name: "Platform Admin",
    email: "admin@demo.com",
    role: "ADMIN",
    joinedAt: daysFromNow(-400),
  },
  {
    id: "u3",
    name: "Aisha Khan",
    email: "aisha@demo.com",
    role: "USER",
    joinedAt: daysFromNow(-60),
  },
  {
    id: "u4",
    name: "David Chen",
    email: "david@demo.com",
    role: "USER",
    blocked: true,
    joinedAt: daysFromNow(-200),
  },
]

export const events: EventItem[] = [
  {
    id: "e1",
    title: "DevFest 2026 — Annual Tech Conference",
    description:
      "A full-day conference on web, cloud, and AI with talks from industry engineers.",
    longDescription:
      "DevFest 2026 brings together 800+ developers for a full day of technical sessions, hands-on codelabs, and networking. Tracks include modern web frameworks, cloud-native architecture, applied AI, and career growth. Lunch and swag included for all registered attendees. Certificates are issued automatically after QR check-in.",
    category: "Technology",
    mode: "IN_PERSON",
    status: "PUBLISHED",
    banner: "/events/tech-conf.png",
    venue: "Grand Convention Center, Hall A",
    city: "Bengaluru",
    startDate: daysFromNow(12, 9),
    endDate: daysFromNow(12, 18),
    capacity: 800,
    registeredCount: 642,
    attendanceCount: 0,
    views: 12840,
    price: 0,
    rating: 4.8,
    ratingCount: 96,
    organizerId: "o1",
    organizerName: "GDG Campus Club",
    organizerVerified: true,
    tags: ["conference", "web", "ai", "cloud"],
  },
  {
    id: "e2",
    title: "HackNight 48 — Campus Hackathon",
    description:
      "48-hour overnight hackathon. Build, ship, and demo with teams of up to 4.",
    longDescription:
      "HackNight 48 is a 48-hour hackathon open to all students and early-career developers. Form teams of up to four, pick a problem statement, and ship a working demo. Mentors available around the clock, with prizes for the top three teams and a special award for best social-impact project.",
    category: "Technology",
    mode: "IN_PERSON",
    status: "PUBLISHED",
    banner: "/events/hackathon.png",
    venue: "Innovation Lab, Block C",
    city: "Pune",
    startDate: daysFromNow(25, 18),
    endDate: daysFromNow(27, 18),
    capacity: 200,
    registeredCount: 187,
    attendanceCount: 0,
    views: 6420,
    price: 0,
    rating: 4.6,
    ratingCount: 41,
    organizerId: "o1",
    organizerName: "GDG Campus Club",
    organizerVerified: true,
    tags: ["hackathon", "students", "prizes"],
  },
  {
    id: "e3",
    title: "Founders Pitch Night",
    description:
      "Ten early-stage startups pitch live to a panel of angel investors.",
    longDescription:
      "An evening where ten selected early-stage startups pitch to a panel of angel investors and VCs. Open to the public — come watch, network, and meet founders. Doors open at 6 PM with networking drinks; pitches start at 7 PM sharp.",
    category: "Business",
    mode: "HYBRID",
    status: "PUBLISHED",
    banner: "/events/startup-pitch.png",
    venue: "The Foundry Auditorium",
    city: "Mumbai",
    startDate: daysFromNow(6, 18),
    endDate: daysFromNow(6, 21),
    capacity: 300,
    registeredCount: 251,
    attendanceCount: 0,
    views: 8930,
    price: 199,
    rating: 4.5,
    ratingCount: 62,
    organizerId: "o2",
    organizerName: "Startup Circle",
    organizerVerified: false,
    tags: ["startup", "investors", "networking"],
  },
  {
    id: "e4",
    title: "Applied AI Workshop: LLMs in Production",
    description:
      "Hands-on workshop covering prompt engineering, RAG, and deployment patterns.",
    longDescription:
      "A hands-on, laptop-required workshop on taking large language models to production. Covers prompt engineering, retrieval-augmented generation, evaluation, and cost/latency optimization. Limited to 60 seats to keep the session interactive. Attendance certificates issued via the platform.",
    category: "Education",
    mode: "ONLINE",
    status: "PUBLISHED",
    banner: "/events/ai-workshop.png",
    venue: "Live on Zoom",
    city: "Online",
    startDate: daysFromNow(3, 14),
    endDate: daysFromNow(3, 18),
    capacity: 60,
    registeredCount: 60,
    attendanceCount: 0,
    views: 5210,
    price: 499,
    rating: 4.9,
    ratingCount: 38,
    organizerId: "o1",
    organizerName: "GDG Campus Club",
    organizerVerified: true,
    tags: ["ai", "workshop", "llm"],
  },
  {
    id: "e5",
    title: "City Charity Marathon 10K",
    description:
      "Run for a cause. All proceeds go to local education NGOs. Medals for finishers.",
    longDescription:
      "The annual City Charity Marathon returns with 10K, 5K, and 3K fun-run categories. All registration proceeds go to local education NGOs. Route starts and ends at Riverside Park with hydration stations every 2 km. Finisher medals and e-certificates for all participants.",
    category: "Sports",
    mode: "IN_PERSON",
    status: "PUBLISHED",
    banner: "/events/city-marathon.png",
    venue: "Riverside Park, Gate 2",
    city: "Delhi",
    startDate: daysFromNow(40, 6),
    endDate: daysFromNow(40, 11),
    capacity: 2000,
    registeredCount: 1340,
    attendanceCount: 0,
    views: 15600,
    price: 299,
    rating: 4.7,
    ratingCount: 210,
    organizerId: "o2",
    organizerName: "Startup Circle",
    organizerVerified: false,
    tags: ["marathon", "charity", "fitness"],
  },
  {
    id: "e6",
    title: "Design Systems Summit",
    description:
      "A one-day summit for product designers and design engineers.",
    longDescription:
      "Design Systems Summit is a single-track, one-day event for product designers and design engineers. Sessions cover token architecture, accessibility at scale, and design-to-code workflows, followed by an evening gallery showcase of community work.",
    category: "Arts",
    mode: "IN_PERSON",
    status: "PUBLISHED",
    banner: "/events/design-summit.png",
    venue: "Museum of Modern Design",
    city: "Bengaluru",
    startDate: daysFromNow(-10, 9),
    endDate: daysFromNow(-10, 18),
    capacity: 250,
    registeredCount: 244,
    attendanceCount: 201,
    views: 9870,
    price: 349,
    rating: 4.4,
    ratingCount: 148,
    organizerId: "o1",
    organizerName: "GDG Campus Club",
    organizerVerified: true,
    tags: ["design", "summit", "ux"],
  },
  {
    id: "e7",
    title: "Cloud Career Bootcamp (Draft)",
    description:
      "Three-evening bootcamp preparing students for cloud certification exams.",
    longDescription:
      "A three-evening bootcamp preparing students and professionals for entry-level cloud certification exams. Includes practice tests, study guides, and a live Q&A with certified engineers.",
    category: "Education",
    mode: "ONLINE",
    status: "DRAFT",
    banner: "/events/ai-workshop.png",
    venue: "Live on Meet",
    city: "Online",
    startDate: daysFromNow(55, 18),
    endDate: daysFromNow(57, 21),
    capacity: 150,
    registeredCount: 0,
    attendanceCount: 0,
    views: 0,
    price: 0,
    rating: 0,
    ratingCount: 0,
    organizerId: "o1",
    organizerName: "GDG Campus Club",
    organizerVerified: true,
    tags: ["cloud", "bootcamp", "certification"],
  },
]

export const registrations: Registration[] = [
  {
    id: "r1",
    eventId: "e1",
    userId: "u1",
    ticketNumber: "EVT-2026-004821",
    qrValue: "REG:r1:e1:u1",
    status: "CONFIRMED",
    attendance: "NOT_MARKED",
    registeredAt: daysFromNow(-4),
  },
  {
    id: "r2",
    eventId: "e4",
    userId: "u1",
    ticketNumber: "EVT-2026-004977",
    qrValue: "REG:r2:e4:u1",
    status: "CONFIRMED",
    attendance: "NOT_MARKED",
    registeredAt: daysFromNow(-2),
  },
  {
    id: "r3",
    eventId: "e6",
    userId: "u1",
    ticketNumber: "EVT-2026-003104",
    qrValue: "REG:r3:e6:u1",
    status: "CONFIRMED",
    attendance: "PRESENT",
    registeredAt: daysFromNow(-30),
  },
  {
    id: "r4",
    eventId: "e6",
    userId: "u2",
    ticketNumber: "EVT-2026-003105",
    qrValue: "REG:r4:e6:u2",
    status: "CONFIRMED",
    attendance: "PRESENT",
    registeredAt: daysFromNow(-28),
  },
  {
    id: "r5",
    eventId: "e1",
    userId: "u2",
    ticketNumber: "EVT-2026-004822",
    qrValue: "REG:r5:e1:u2",
    status: "CONFIRMED",
    attendance: "NOT_MARKED",
    registeredAt: daysFromNow(-5),
  },
  {
    id: "r6",
    eventId: "e1",
    userId: "u3",
    ticketNumber: "EVT-2026-004823",
    qrValue: "REG:r6:e1:u3",
    status: "CONFIRMED",
    attendance: "NOT_MARKED",
    registeredAt: daysFromNow(-3),
  },
  {
    id: "r7",
    eventId: "e6",
    userId: "u3",
    ticketNumber: "EVT-2026-003106",
    qrValue: "REG:r7:e6:u3",
    status: "CONFIRMED",
    attendance: "LATE",
    registeredAt: daysFromNow(-25),
  },
]

export const certificates: Certificate[] = [
  {
    id: "c1",
    eventId: "e6",
    eventTitle: "Design Systems Summit",
    userId: "u1",
    userName: "Rahul Sharma",
    issuedAt: daysFromNow(-9),
    certificateNumber: "CERT-2026-01187",
  },
  {
    id: "c2",
    eventId: "e6",
    eventTitle: "Design Systems Summit",
    userId: "u2",
    userName: "Priya Patel",
    issuedAt: daysFromNow(-9),
    certificateNumber: "CERT-2026-01188",
  },
]

export const notifications: AppNotification[] = [
  {
    id: "n1",
    userId: "u1",
    type: "CERTIFICATE",
    title: "Certificate ready",
    message:
      "Your certificate for Design Systems Summit is ready to download.",
    read: false,
    createdAt: daysFromNow(-9, 12),
  },
  {
    id: "n2",
    userId: "u1",
    type: "REMINDER",
    title: "Event starting soon",
    message: "Applied AI Workshop: LLMs in Production starts in 3 days.",
    read: false,
    createdAt: daysFromNow(0, 8),
  },
  {
    id: "n3",
    userId: "u1",
    type: "REGISTRATION",
    title: "Registration confirmed",
    message: "You are registered for DevFest 2026. Your QR ticket is ready.",
    read: true,
    createdAt: daysFromNow(-4, 15),
  },
  {
    id: "n4",
    userId: "u1",
    type: "UPDATE",
    title: "Venue update",
    message: "DevFest 2026 has moved to Hall A at the Grand Convention Center.",
    read: true,
    createdAt: daysFromNow(-1, 10),
  },
]

export const feedbacks: Feedback[] = [
  {
    id: "f1",
    eventId: "e6",
    userId: "u2",
    userName: "Priya Patel",
    rating: 5,
    review:
      "Fantastic sessions, especially the token architecture talk. Check-in with QR was seamless.",
    createdAt: daysFromNow(-9, 20),
  },
  {
    id: "f2",
    eventId: "e6",
    userId: "u3",
    userName: "Aisha Khan",
    rating: 4,
    review: "Great speakers and venue. Lunch queue was a bit long.",
    createdAt: daysFromNow(-8, 9),
  },
  {
    id: "f3",
    eventId: "e1",
    userId: "u2",
    userName: "Priya Patel",
    rating: 5,
    review: "Attended last year — the best community conference in the city.",
    createdAt: daysFromNow(-60, 11),
  },
]

// demo credentials shown on the login page
export const demoAccounts = [
  { role: "USER", email: "user@demo.com", password: "password123" },
  { role: "ORGANIZER", email: "organizer@demo.com", password: "password123" },
  { role: "ADMIN", email: "admin@demo.com", password: "password123" },
] as const
